-- ====================================================================
-- ACTUARIAL PORTFOLIO: SEED DATA (CS1 & CM1 REPRESENTATIVE DATA)
-- Description: CSO-like mortality rates, policy underwriting, and claims.
-- ====================================================================

-- A. SEED MORTALITY LIFE TABLE
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (18, 'Male', 0, 0.000420, 67.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (18, 'Male', 1, 0.000966, 61.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (18, 'Female', 0, 0.000350, 71.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (18, 'Female', 1, 0.000805, 65.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (19, 'Male', 0, 0.000453, 66.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (19, 'Male', 1, 0.001041, 60.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (19, 'Female', 0, 0.000377, 70.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (19, 'Female', 1, 0.000868, 64.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (20, 'Male', 0, 0.000488, 65.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (20, 'Male', 1, 0.001122, 59.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (20, 'Female', 0, 0.000407, 69.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (20, 'Female', 1, 0.000935, 63.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (21, 'Male', 0, 0.000526, 64.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (21, 'Male', 1, 0.001210, 58.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (21, 'Female', 0, 0.000438, 68.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (21, 'Female', 1, 0.001008, 62.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (22, 'Male', 0, 0.000567, 63.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (22, 'Male', 1, 0.001304, 57.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (22, 'Female', 0, 0.000472, 67.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (22, 'Female', 1, 0.001087, 61.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (23, 'Male', 0, 0.000611, 62.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (23, 'Male', 1, 0.001406, 56.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (23, 'Female', 0, 0.000509, 66.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (23, 'Female', 1, 0.001171, 60.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (24, 'Male', 0, 0.000659, 61.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (24, 'Male', 1, 0.001515, 55.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (24, 'Female', 0, 0.000549, 65.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (24, 'Female', 1, 0.001262, 59.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (25, 'Male', 0, 0.000710, 60.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (25, 'Male', 1, 0.001633, 54.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (25, 'Female', 0, 0.000592, 64.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (25, 'Female', 1, 0.001361, 58.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (26, 'Male', 0, 0.000765, 59.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (26, 'Male', 1, 0.001760, 53.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (26, 'Female', 0, 0.000638, 63.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (26, 'Female', 1, 0.001467, 57.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (27, 'Male', 0, 0.000825, 58.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (27, 'Male', 1, 0.001897, 52.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (27, 'Female', 0, 0.000687, 62.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (27, 'Female', 1, 0.001581, 56.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (28, 'Male', 0, 0.000889, 57.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (28, 'Male', 1, 0.002045, 51.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (28, 'Female', 0, 0.000741, 61.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (28, 'Female', 1, 0.001704, 55.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (29, 'Male', 0, 0.000958, 56.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (29, 'Male', 1, 0.002204, 50.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (29, 'Female', 0, 0.000799, 60.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (29, 'Female', 1, 0.001837, 54.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (30, 'Male', 0, 0.001033, 55.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (30, 'Male', 1, 0.002376, 49.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (30, 'Female', 0, 0.000861, 59.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (30, 'Female', 1, 0.001980, 53.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (31, 'Male', 0, 0.001113, 54.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (31, 'Male', 1, 0.002561, 48.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (31, 'Female', 0, 0.000928, 58.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (31, 'Female', 1, 0.002134, 52.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (32, 'Male', 0, 0.001200, 53.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (32, 'Male', 1, 0.002760, 47.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (32, 'Female', 0, 0.001000, 57.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (32, 'Female', 1, 0.002300, 51.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (33, 'Male', 0, 0.001294, 52.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (33, 'Male', 1, 0.002975, 46.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (33, 'Female', 0, 0.001078, 56.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (33, 'Female', 1, 0.002480, 50.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (34, 'Male', 0, 0.001394, 51.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (34, 'Male', 1, 0.003207, 45.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (34, 'Female', 0, 0.001162, 55.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (34, 'Female', 1, 0.002673, 49.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (35, 'Male', 0, 0.001503, 50.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (35, 'Male', 1, 0.003457, 44.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (35, 'Female', 0, 0.001253, 54.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (35, 'Female', 1, 0.002881, 48.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (36, 'Male', 0, 0.001620, 49.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (36, 'Male', 1, 0.003726, 43.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (36, 'Female', 0, 0.001350, 53.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (36, 'Female', 1, 0.003105, 47.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (37, 'Male', 0, 0.001746, 48.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (37, 'Male', 1, 0.004016, 42.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (37, 'Female', 0, 0.001455, 52.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (37, 'Female', 1, 0.003347, 46.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (38, 'Male', 0, 0.001882, 47.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (38, 'Male', 1, 0.004329, 41.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (38, 'Female', 0, 0.001569, 51.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (38, 'Female', 1, 0.003608, 45.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (39, 'Male', 0, 0.002029, 46.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (39, 'Male', 1, 0.004666, 40.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (39, 'Female', 0, 0.001691, 50.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (39, 'Female', 1, 0.003889, 44.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (40, 'Male', 0, 0.002187, 45.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (40, 'Male', 1, 0.005030, 39.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (40, 'Female', 0, 0.001822, 49.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (40, 'Female', 1, 0.004192, 43.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (41, 'Male', 0, 0.002357, 44.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (41, 'Male', 1, 0.005422, 38.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (41, 'Female', 0, 0.001964, 48.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (41, 'Female', 1, 0.004518, 42.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (42, 'Male', 0, 0.002541, 43.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (42, 'Male', 1, 0.005844, 37.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (42, 'Female', 0, 0.002117, 47.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (42, 'Female', 1, 0.004870, 41.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (43, 'Male', 0, 0.002739, 42.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (43, 'Male', 1, 0.006299, 36.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (43, 'Female', 0, 0.002282, 46.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (43, 'Female', 1, 0.005249, 40.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (44, 'Male', 0, 0.002952, 41.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (44, 'Male', 1, 0.006790, 35.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (44, 'Female', 0, 0.002460, 45.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (44, 'Female', 1, 0.005658, 39.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (45, 'Male', 0, 0.003182, 40.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (45, 'Male', 1, 0.007319, 34.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (45, 'Female', 0, 0.002652, 44.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (45, 'Female', 1, 0.006099, 38.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (46, 'Male', 0, 0.003430, 39.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (46, 'Male', 1, 0.007889, 33.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (46, 'Female', 0, 0.002858, 43.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (46, 'Female', 1, 0.006574, 37.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (47, 'Male', 0, 0.003697, 38.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (47, 'Male', 1, 0.008503, 32.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (47, 'Female', 0, 0.003081, 42.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (47, 'Female', 1, 0.007086, 36.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (48, 'Male', 0, 0.003985, 37.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (48, 'Male', 1, 0.009165, 31.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (48, 'Female', 0, 0.003321, 41.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (48, 'Female', 1, 0.007638, 35.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (49, 'Male', 0, 0.004295, 36.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (49, 'Male', 1, 0.009879, 30.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (49, 'Female', 0, 0.003579, 40.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (49, 'Female', 1, 0.008232, 34.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (50, 'Male', 0, 0.004630, 35.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (50, 'Male', 1, 0.010648, 29.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (50, 'Female', 0, 0.003858, 39.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (50, 'Female', 1, 0.008874, 33.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (51, 'Male', 0, 0.004990, 34.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (51, 'Male', 1, 0.011478, 28.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (51, 'Female', 0, 0.004159, 38.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (51, 'Female', 1, 0.009565, 32.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (52, 'Male', 0, 0.005379, 33.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (52, 'Male', 1, 0.012372, 27.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (52, 'Female', 0, 0.004482, 37.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (52, 'Female', 1, 0.010310, 31.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (53, 'Male', 0, 0.005798, 32.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (53, 'Male', 1, 0.013335, 26.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (53, 'Female', 0, 0.004832, 36.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (53, 'Female', 1, 0.011113, 30.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (54, 'Male', 0, 0.006249, 31.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (54, 'Male', 1, 0.014374, 25.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (54, 'Female', 0, 0.005208, 35.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (54, 'Female', 1, 0.011978, 29.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (55, 'Male', 0, 0.006736, 30.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (55, 'Male', 1, 0.015493, 24.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (55, 'Female', 0, 0.005614, 34.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (55, 'Female', 1, 0.012911, 28.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (56, 'Male', 0, 0.007261, 29.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (56, 'Male', 1, 0.016700, 23.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (56, 'Female', 0, 0.006051, 33.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (56, 'Female', 1, 0.013917, 27.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (57, 'Male', 0, 0.007826, 28.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (57, 'Male', 1, 0.018001, 22.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (57, 'Female', 0, 0.006522, 32.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (57, 'Female', 1, 0.015001, 26.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (58, 'Male', 0, 0.008436, 27.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (58, 'Male', 1, 0.019403, 21.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (58, 'Female', 0, 0.007030, 31.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (58, 'Female', 1, 0.016169, 25.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (59, 'Male', 0, 0.009093, 26.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (59, 'Male', 1, 0.020914, 20.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (59, 'Female', 0, 0.007577, 30.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (59, 'Female', 1, 0.017428, 24.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (60, 'Male', 0, 0.009801, 25.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (60, 'Male', 1, 0.022543, 19.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (60, 'Female', 0, 0.008168, 29.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (60, 'Female', 1, 0.018786, 23.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (61, 'Male', 0, 0.010565, 24.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (61, 'Male', 1, 0.024298, 18.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (61, 'Female', 0, 0.008804, 28.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (61, 'Female', 1, 0.020249, 22.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (62, 'Male', 0, 0.011387, 23.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (62, 'Male', 1, 0.026191, 17.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (62, 'Female', 0, 0.009489, 27.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (62, 'Female', 1, 0.021826, 21.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (63, 'Male', 0, 0.012274, 22.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (63, 'Male', 1, 0.028231, 16.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (63, 'Female', 0, 0.010228, 26.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (63, 'Female', 1, 0.023526, 20.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (64, 'Male', 0, 0.013230, 21.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (64, 'Male', 1, 0.030429, 15.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (64, 'Female', 0, 0.011025, 25.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (64, 'Female', 1, 0.025358, 19.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (65, 'Male', 0, 0.014261, 20.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (65, 'Male', 1, 0.032799, 14.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (65, 'Female', 0, 0.011884, 24.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (65, 'Female', 1, 0.027333, 18.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (66, 'Male', 0, 0.015371, 19.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (66, 'Male', 1, 0.035354, 13.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (66, 'Female', 0, 0.012809, 23.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (66, 'Female', 1, 0.029462, 17.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (67, 'Male', 0, 0.016568, 18.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (67, 'Male', 1, 0.038107, 12.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (67, 'Female', 0, 0.013807, 22.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (67, 'Female', 1, 0.031756, 16.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (68, 'Male', 0, 0.017859, 17.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (68, 'Male', 1, 0.041075, 11.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (68, 'Female', 0, 0.014882, 21.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (68, 'Female', 1, 0.034229, 15.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (69, 'Male', 0, 0.019250, 16.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (69, 'Male', 1, 0.044274, 10.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (69, 'Female', 0, 0.016041, 20.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (69, 'Female', 1, 0.036895, 14.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (70, 'Male', 0, 0.020749, 15.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (70, 'Male', 1, 0.047723, 9.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (70, 'Female', 0, 0.017291, 19.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (70, 'Female', 1, 0.039769, 13.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (71, 'Male', 0, 0.022365, 14.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (71, 'Male', 1, 0.051440, 8.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (71, 'Female', 0, 0.018638, 18.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (71, 'Female', 1, 0.042866, 12.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (72, 'Male', 0, 0.024107, 13.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (72, 'Male', 1, 0.055446, 7.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (72, 'Female', 0, 0.020089, 17.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (72, 'Female', 1, 0.046205, 11.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (73, 'Male', 0, 0.025984, 12.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (73, 'Male', 1, 0.059764, 6.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (73, 'Female', 0, 0.021654, 16.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (73, 'Female', 1, 0.049804, 10.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (74, 'Male', 0, 0.028008, 11.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (74, 'Male', 1, 0.064419, 5.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (74, 'Female', 0, 0.023340, 15.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (74, 'Female', 1, 0.053682, 9.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (75, 'Male', 0, 0.030190, 10.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (75, 'Male', 1, 0.069436, 4.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (75, 'Female', 0, 0.025158, 14.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (75, 'Female', 1, 0.057864, 8.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (76, 'Male', 0, 0.032541, 9.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (76, 'Male', 1, 0.074844, 3.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (76, 'Female', 0, 0.027117, 13.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (76, 'Female', 1, 0.062370, 7.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (77, 'Male', 0, 0.035075, 8.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (77, 'Male', 1, 0.080673, 2.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (77, 'Female', 0, 0.029229, 12.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (77, 'Female', 1, 0.067228, 6.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (78, 'Male', 0, 0.037807, 7.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (78, 'Male', 1, 0.086957, 1.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (78, 'Female', 0, 0.031506, 11.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (78, 'Female', 1, 0.072464, 5.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (79, 'Male', 0, 0.040752, 6.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (79, 'Male', 1, 0.093729, 1.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (79, 'Female', 0, 0.033960, 10.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (79, 'Female', 1, 0.078108, 4.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (80, 'Male', 0, 0.043926, 5.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (80, 'Male', 1, 0.101029, 1.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (80, 'Female', 0, 0.036605, 9.0);
INSERT INTO mortality_life_table (age, gender, is_smoker, qx, ex) VALUES (80, 'Female', 1, 0.084191, 3.0);

-- B. SEED POLICY PORTFOLIO
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1001', 'Patricia Smith', 37, 'Female', 0, 100000, 287, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1002', 'Sarah Williams', 57, 'Female', 0, 150000, 1245, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1003', 'Linda Martin', 58, 'Female', 0, 500000, 4162, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1004', 'Sarah Thomas', 34, 'Female', 0, 100000, 254, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1005', 'Jennifer Thomas', 41, 'Female', 0, 200000, 572, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1006', 'Patricia Williams', 44, 'Female', 0, 300000, 969, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1007', 'William Johnson', 49, 'Male', 1, 250000, 2960, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1008', 'John Jackson', 38, 'Male', 0, 200000, 553, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1009', 'Charles Davis', 65, 'Female', 0, 200000, 2853, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1010', 'John Garcia', 26, 'Female', 0, 200000, 267, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1011', 'Jennifer Anderson', 42, 'Female', 0, 500000, 1337, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1012', 'John White', 60, 'Female', 0, 150000, 1529, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1013', 'Joseph Taylor', 37, 'Male', 0, 300000, 722, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1014', 'Linda Martinez', 23, 'Female', 0, 200000, 237, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1015', 'Richard Rodriguez', 24, 'Female', 1, 500000, 846, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1016', 'David Davis', 61, 'Female', 1, 500000, 11763, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1017', 'Joseph Jones', 36, 'Female', 0, 300000, 586, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1018', 'William Thompson', 47, 'Male', 0, 150000, 758, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1019', 'Robert Martin', 51, 'Female', 0, 100000, 598, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1020', 'Robert Miller', 63, 'Female', 0, 250000, 3061, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1021', 'Karen Hernandez', 53, 'Female', 0, 100000, 676, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1022', 'Patricia Jackson', 37, 'Male', 0, 200000, 522, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1023', 'Susan Miller', 49, 'Female', 0, 500000, 2178, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1024', 'William Martin', 31, 'Male', 0, 500000, 760, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1025', 'Elizabeth Martin', 58, 'Female', 0, 150000, 1333, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1026', 'Sarah Martin', 20, 'Male', 0, 100000, 176, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1027', 'Barbara Wilson', 35, 'Female', 1, 100000, 451, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1028', 'John Moore', 24, 'Male', 0, 150000, 234, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1029', 'Robert Moore', 55, 'Female', 0, 300000, 2057, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1030', 'Susan Davis', 54, 'Male', 0, 500000, 3713, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1031', 'Elizabeth Taylor', 62, 'Male', 0, 300000, 4049, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1032', 'Joseph Brown', 35, 'Female', 0, 300000, 552, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1033', 'Sarah Garcia', 57, 'Female', 0, 500000, 3870, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1034', 'Mary Garcia', 24, 'Male', 1, 100000, 294, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1035', 'Thomas Garcia', 37, 'Male', 0, 150000, 421, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1036', 'Charles Thompson', 50, 'Female', 0, 250000, 1229, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1037', 'Michael Brown', 26, 'Male', 0, 250000, 340, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1038', 'Joseph Johnson', 63, 'Male', 0, 100000, 1532, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1039', 'Richard Martinez', 26, 'Female', 0, 250000, 303, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1040', 'Robert Thomas', 31, 'Female', 0, 100000, 227, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1041', 'Joseph Jackson', 26, 'Female', 1, 100000, 289, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1042', 'John Garcia', 30, 'Female', 0, 250000, 367, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1043', 'Mary Miller', 44, 'Female', 0, 250000, 827, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1044', 'Elizabeth Thomas', 64, 'Male', 1, 300000, 10618, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1045', 'Jessica Jones', 32, 'Female', 1, 300000, 914, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1046', 'Sarah Johnson', 40, 'Female', 0, 300000, 749, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1047', 'Thomas Miller', 23, 'Male', 0, 150000, 225, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1048', 'John White', 24, 'Male', 0, 100000, 196, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1049', 'Charles Garcia', 57, 'Male', 0, 250000, 2370, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1050', 'Charles Thompson', 53, 'Female', 0, 500000, 2898, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1051', 'David Garcia', 36, 'Female', 0, 200000, 431, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1052', 'Joseph Martinez', 24, 'Female', 0, 300000, 309, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1053', 'Patricia Williams', 54, 'Female', 0, 200000, 1318, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1054', 'John Garcia', 43, 'Female', 0, 300000, 907, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1055', 'Elizabeth White', 61, 'Male', 0, 300000, 3765, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1056', 'Elizabeth Brown', 28, 'Female', 1, 500000, 1100, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1057', 'Sarah Jones', 37, 'Female', 0, 200000, 455, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1058', 'Michael Rodriguez', 52, 'Female', 1, 100000, 1306, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1059', 'John Thomas', 37, 'Female', 0, 150000, 371, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1060', 'William Miller', 48, 'Male', 0, 100000, 578, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1061', 'Patricia Williams', 64, 'Male', 0, 200000, 3163, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1062', 'Charles Jackson', 29, 'Female', 0, 200000, 304, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1063', 'Mary Anderson', 33, 'Male', 0, 200000, 418, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1064', 'Sarah Thomas', 59, 'Male', 1, 150000, 3728, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1065', 'Jennifer Miller', 46, 'Female', 0, 200000, 777, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1066', 'Susan Garcia', 37, 'Female', 0, 250000, 538, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1067', 'Mary Moore', 34, 'Female', 1, 200000, 735, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1068', 'Elizabeth Garcia', 34, 'Female', 0, 200000, 387, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1069', 'William Williams', 37, 'Female', 0, 500000, 957, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1070', 'Sarah Martinez', 21, 'Female', 1, 150000, 294, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1071', 'Charles Rodriguez', 22, 'Female', 0, 500000, 392, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1072', 'David Thomas', 58, 'Male', 0, 300000, 3030, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1073', 'Michael Rodriguez', 22, 'Male', 0, 300000, 316, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1074', 'Michael Anderson', 47, 'Female', 0, 200000, 829, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1075', 'Karen Martinez', 62, 'Male', 0, 200000, 2739, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1076', 'Thomas Wilson', 62, 'Female', 0, 200000, 2303, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1077', 'Sarah Jones', 32, 'Female', 1, 500000, 1443, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1078', 'Jennifer White', 56, 'Female', 0, 100000, 816, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1079', 'Elizabeth Wilson', 33, 'Female', 0, 500000, 740, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1080', 'David Hernandez', 48, 'Female', 0, 250000, 1075, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1081', 'Jennifer Williams', 38, 'Male', 0, 200000, 553, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1082', 'John Garcia', 63, 'Female', 0, 150000, 1884, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1083', 'James Johnson', 35, 'Male', 0, 100000, 293, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1084', 'Joseph Thomas', 60, 'Male', 0, 250000, 2938, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1085', 'Jessica Taylor', 35, 'Female', 0, 100000, 264, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1086', 'Susan Garcia', 31, 'Male', 0, 250000, 440, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1087', 'Mary Jackson', 35, 'Male', 0, 150000, 379, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1088', 'Joseph Martin', 55, 'Male', 1, 250000, 4574, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1089', 'Karen Martin', 47, 'Male', 0, 150000, 758, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1090', 'Jessica Hernandez', 36, 'Male', 0, 200000, 493, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1091', 'Thomas Moore', 60, 'Female', 0, 500000, 4816, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1092', 'Elizabeth Garcia', 37, 'Female', 1, 100000, 505, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1093', 'Robert Jones', 34, 'Female', 0, 150000, 320, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1094', 'John Thomas', 46, 'Female', 0, 100000, 449, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1095', 'Michael Thomas', 44, 'Male', 0, 500000, 1817, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1096', 'James Thompson', 44, 'Female', 1, 200000, 1421, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1097', 'Richard Thomas', 54, 'Male', 0, 300000, 2276, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1098', 'Linda Moore', 34, 'Female', 0, 250000, 454, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1099', 'David Taylor', 30, 'Male', 1, 300000, 940, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1100', 'Sarah Smith', 45, 'Male', 0, 100000, 486, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1101', 'Susan Jones', 49, 'Female', 0, 200000, 943, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1102', 'Michael Hernandez', 40, 'Female', 1, 200000, 1084, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1103', 'Susan Rodriguez', 25, 'Female', 0, 100000, 188, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1104', 'Barbara Garcia', 61, 'Female', 1, 100000, 2449, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1105', 'James Garcia', 32, 'Male', 0, 150000, 327, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1106', 'Robert Moore', 62, 'Female', 1, 250000, 6395, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1107', 'William Anderson', 30, 'Male', 1, 500000, 1486, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1108', 'Patricia Miller', 39, 'Female', 0, 200000, 509, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1109', 'Charles Taylor', 45, 'Male', 0, 300000, 1218, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1110', 'Linda Brown', 64, 'Male', 1, 300000, 10618, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1111', 'Patricia Thompson', 22, 'Female', 0, 200000, 229, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1112', 'John Martin', 61, 'Female', 0, 250000, 2651, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1113', 'Patricia Thomas', 43, 'Male', 0, 500000, 1695, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1114', 'Robert Thomas', 31, 'Male', 1, 200000, 709, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1115', 'Karen Jackson', 50, 'Female', 0, 300000, 1451, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1116', 'William Martinez', 35, 'Male', 0, 250000, 552, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1117', 'Linda Hernandez', 56, 'Male', 0, 100000, 955, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1118', 'Jessica Martinez', 31, 'Female', 0, 200000, 333, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1119', 'David Rodriguez', 58, 'Male', 0, 100000, 1090, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1120', 'Thomas Davis', 25, 'Female', 0, 300000, 324, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1121', 'Linda Moore', 61, 'Male', 0, 100000, 1335, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1122', 'John Wilson', 34, 'Female', 0, 500000, 788, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1123', 'Charles Anderson', 50, 'Male', 0, 500000, 2782, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1124', 'Sarah Martinez', 42, 'Male', 0, 200000, 704, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1125', 'Linda Brown', 32, 'Female', 0, 500000, 695, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1126', 'Jennifer Davis', 33, 'Male', 0, 300000, 566, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1127', 'Thomas White', 38, 'Male', 0, 200000, 553, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1128', 'Linda Anderson', 31, 'Female', 0, 150000, 280, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1129', 'William Johnson', 23, 'Male', 0, 150000, 225, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1130', 'Jessica Brown', 20, 'Male', 0, 250000, 260, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1131', 'David Miller', 23, 'Female', 1, 100000, 255, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1132', 'John Taylor', 51, 'Female', 0, 100000, 598, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1133', 'Robert Jones', 56, 'Male', 0, 150000, 1372, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1134', 'Patricia Jackson', 46, 'Male', 0, 150000, 712, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1135', 'Thomas Taylor', 48, 'Male', 0, 300000, 1495, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1136', 'Susan Wilson', 56, 'Male', 0, 500000, 4295, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1137', 'Patricia Davis', 60, 'Female', 0, 150000, 1529, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1138', 'Linda Miller', 55, 'Female', 0, 250000, 1734, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1139', 'Karen Moore', 38, 'Female', 0, 200000, 481, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1140', 'Joseph Williams', 63, 'Female', 0, 500000, 6001, 'Substandard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1141', 'Charles Davis', 47, 'Female', 0, 150000, 651, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1142', 'William Jones', 24, 'Female', 0, 300000, 309, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1143', 'Charles Wilson', 48, 'Female', 0, 500000, 2029, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1144', 'Richard Rodriguez', 52, 'Male', 0, 300000, 1976, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1145', 'Mary Thomas', 40, 'Male', 0, 150000, 497, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1146', 'Charles Thompson', 21, 'Male', 0, 200000, 241, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1147', 'Charles Johnson', 31, 'Female', 0, 200000, 333, 'Preferred', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1148', 'Jennifer Thompson', 47, 'Male', 0, 100000, 545, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1149', 'Jessica Anderson', 46, 'Female', 0, 150000, 613, 'Standard', 'Active');
INSERT INTO policies (policy_id, holder_name, holder_age, holder_gender, is_smoker, sum_assured, annual_premium, risk_class, status) VALUES ('POL-1150', 'David Thomas', 64, 'Female', 0, 250000, 3290, 'Substandard', 'Active');

-- C. SEED CLAIMS
INSERT INTO claims (claim_id, policy_id, claim_amount, accident_date, report_delay_days) VALUES ('CLM-2001', 'POL-1072', 300000, '2025-08-23', 61);
UPDATE policies SET status = 'Claimed' WHERE policy_id = 'POL-1072';